### ISSUE TITLE
無駄な dependency が入っている (am-coffee-time)

### ISSUE THREAD

**Issue by kt3k** [ampcpmgp/amdeven#12]
https://github.com/ampcpmgp/amdev/blob/master/modules/am-coffee-time/package.json

- webpack で固めている module は devDepenedency に移せるはずと思います (jquery, riot など)

**Comment by ampcpmgp** [comment]
あっ　ここは、webpackでnode_modulesをbundleしないファイルと、するファイルの２種類を作っているため、bundleしていない用のimport/requireのため、残す必要がありました！
https://github.com/ampcpmgp/amdev/blob/ffd397103f25ae8a739efb9bcd0385d37087dfc2/app/ModuleCompiler.coffee#L26-L42

他の未使用moduleなどは整理できそうです。

**Comment by ampcpmgp** [comment]
一旦解決済み！
